In [2]:
import sys
import pandas as pd

sys.path.append("../../..")
import lemur.datasets as lds
import lemur.plotters as lpl

In [21]:
#hbn = pd.read_csv("../../../../DMZ/hbn.csv", dtype="unicode")
#for c in hbn.columns:
#    if '"' in c:
#        del hbn[c]
#hbn.to_csv("../../../../DMZ/hbn_cleaned.csv")

In [3]:
CDS = lds.CSVDataSet("../../../../kpf/hbn_cleaned.csv",
                     index_column = "Identifiers",
                     column_level_names = ("Instrument", "Variable"))

In [4]:
CDS.D.columns.names = ("Instrument", "Variable")

In [5]:
CDS.D.columns.names

FrozenList(['Instrument', 'Variable'])

In [6]:
CDS.getResource(CDS.D.index[0])

array([          nan,   91.        ,  126.        ,    1.        ,
          5.        ,           nan,    3.        ,           nan,
         58.5       ,    6.        ,           nan,           nan,
                 nan,   13.        ,   23.        ,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,           nan,           nan,
                 nan,           nan,   14.        ,   44.        ,
         65.57      ,           nan,           nan,           nan,
                 nan,           nan,   17.        ,           nan,
                 nan,   14.        ,           nan,           nan,
                 nan,    0.        ,    1.        ,           nan,
                 nan,           nan,   82.        ,           nan,
                 nan,           nan,    1.        ,    0.        ,
          2.        ,    2.        ,    0.        ,    0.        ,
          0.        ,    2.        ,    0.        ,   10.     

In [26]:
CDS.getColumnValues(12)

array([], dtype=float64)

In [27]:
CDS.getColumnValues(("ACE", "ACE_01"))

array([ 0.,  1.])

In [28]:
CDS.getColumnDistribution(3)

(array([ 0.,  1.]), [19, 8])

In [8]:
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
lpl.ColumnDistributionPlotter(CDS).plot(13)

In [30]:
print(CDS.getColumnDescription(10, sep="<br>"))

Instrument: ACE<br>Variable: ACE_Score


In [34]:
def xlsxToHTML(path):
    workbook = load_workbook(path + '.xlsx')
    worksheet = workbook.get_active_sheet()

    html_data = """
    <html>
        <head>
            <title>
            %s
            </title>
            <link rel="stylesheet"
                  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
                  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
                  crossorigin="anonymous">
        </head>
        <body>
            <h3>
            %s
            <h3>
        <table class='table'>
    """ % (worksheet['A1'].value, worksheet['A1'].value)
    first = False
    for row in worksheet:
        if first == False:
            first = True
            continue
        html_data += "      <tr>\n"
        for cell in row:
            if cell.value is None:
                html_data += '            <td>' + ' ' + '</td>\n'
            else:
                html_data += '            <td>' + str(cell.value) + '</td>\n'
        html_data += '    </tr>\n'
    html_data += "</table></body></html>"

    with open(path + ".html", "w") as html_fil:
        html_fil.write(html_data)

In [40]:
base = '../../../../DMZ/descriptions'
import numpy as np
tests = np.unique(list(map(lambda x: x[0], CDS.D.columns.values)))
for t in tests:
    try:
        xlsxToHTML(os.path.join(base, t))
    except:
        print("No info for", t)

/usr/local/lib/python3.5/dist-packages/openpyxl/reader/worksheet.py:312: UserWarning:

Unknown extension is not supported and will be removed



No info for CELF5_Meta
No info for DSM5_Dx
No info for MRI_Track
No info for Pegboard
No info for PreInt_Demos_Fam
No info for PreInt_Demos_Home
No info for Pregnancy
No info for SWAN
No info for TRF_Pre
No info for Unnamed: 0
